#!/usr/bin/env perl
use Mojolicious::Lite;

use FindBin '$Bin';
use lib "$Bin/lib";
use TagNotes;

plugin 'Config';

# configure tagnotes helper
my $tagnotes = TagNotes->new(notes_dir => app->config->{notes_dir});
app->helper(tagnotes => sub {$tagnotes});

get '/' => sub {
    my $c = shift;
    $c->render(template => 'index');
};

app->start;
